### ISSUE TITLE
Template name casing error when running in prod

### ISSUE THREAD

**Issue by emt14** [mbknor/faster-groovy-templates#21] opened 2012-05-14 07:43 UTC
OS: Windows server 2008 Standard x64
Java: 1.6_31 x64
Mode: Prod
Precompiled: true
## Play 1.2.x

Error Execution exception
NoClassDefFoundError occured : play/template2/generated_templates/GTTemplate__app_views_GM_projectStatus_html (wrong name: play/template2/generated_templates/GTTemplate__app_views_Gm_projectStatus_html)

play.exceptions.JavaExecutionException: play/template2/generated_templates/GTTemplate__app_views_GM_projectStatus_html (wrong name: play/template2/generated_templates/GTTemplate__app_views_Gm_projectStatus_html)
    at play.mvc.ActionInvoker.invoke(ActionInvoker.java:231)
##     at Invocation.HTTP Request(Play!)

Issue: Gm view directory and GM controller casing seem to produce the error above. Running in dev mode everything works fine. When deploying in prod however it seems that the casing prevents the template from being found.
Work around: Rename view directory to capital letters and rebuild the app.

**Comment by mbknor** [comment] 2012-05-14 07:48
Thanks for good report.
I'll look into it.

**Comment by mbknor** [comment] 2012-05-14 08:01
What is the exact name and path(with correct casing) to your projectStatus.html templatefile?

Can you please attach the complete stacktrace unmodified?

**Comment by mbknor** [comment] 2012-05-14 08:25
Can it be the case that there is a casing missmatch between your controller and view folder?
And that it works when in dev mode, since windows file system does not care about different casing?
But when you are in prod mode, when I read in the filenames, fastergt cares about case-differences when I look for template in hashmap?

Can you supply the complete qualified controllername (package and classname) for the controller which renders the problem template.

**Comment by mbknor** [comment] 2012-05-14 20:18
I managed to reproduce the error when naming the controller 'GM' and the view folder 'Gm'.

The view folder is supposed to have the exact same name as the controller - that would fix your issue.

But I agree that the way it "works" now is really confusing so I'll try to fix it.

**Comment by mbknor** [comment] 2012-05-15 06:04
I have now fixed the problem but I'm not releasing a new version of the plugin yet, so you have to download it from github manually for the time being.

**Closed as completed by mbknor** 2012-05-15 06:04 UTC
